<%@ Page Title="Pagina inicial" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="treinamentoInicialAspNetCompleto._Default" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1><%: Title %>. JOGOS - </h1>
                <h2>Gestão de Jogos.</h2>
            </hgroup>
            <p>
                Para saber mais sobre o ASP.NET, visite <a href="http://asp.net" title="ASP.NET Website">http://asp.net</a>.
                A página apresenta <mark>vídeos, tutoriais e amostras</mark> para ajudá-lo a obter o máximo do ASP.NET.
                Se você tiver alguma dúvida sobre o ASP.NET, visite
                <a href="http://forums.asp.net/18.aspx" title="ASP.NET Forum">nossos fóruns</a>.
            </p>
        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">

    <table>
        <tr>
            <td rowspan = 2>
                <fieldset id="fsControle">
                    <legend>Escolha um Botão:</legend>
                    <asp:Button ID="btnDesvCon" runat="server" Text="Desvio Condicional" height="43px" Width="330px" OnClick="btnDesvCon_Click" />
                    <asp:Button ID="btnImport" runat="server" Text="Importação TXT" height="43px" width="330px" OnClick="btnImport_Click" />
                    <asp:Button ID="btnBDC" runat="server" Text="Banco Conectado" height="43px" width="330px" OnClick="btnBDC_Click" />
                    <asp:Button ID="btnBDD" runat="server" Text="Banco Desconectado" height="43px" width="330px" OnClick="btnBDD_Click1" />
                    <asp:Button ID="btnConsultar" runat="server" Text="Consultar" height="43px" width="330px" OnClick="btnConsultar_Click" />
                    <asp:Button ID="btnInserir" runat="server" Text="Inserir" height="43px" width="330px" OnClick="btnInserir_Click" />
                    <asp:Button ID="btnExcluir" runat="server" Text="Excluir" height="43px" width="330px" OnClick="btnExcluir_Click" />
                    <asp:Button ID="btnAlterar" runat="server" Text="Alterar" height="43px" width="330px" OnClick="btnAlterar_Click" />
                </fieldset>
            </td>
            <td>
                <fieldset id="fsArquivoTexto">
                    <legend>Conteudo de Importação do Arquivo Texto</legend>
                    <asp:ListBox ID="lstbxJogos" runat="server" Height="39px" Width="350px"></asp:ListBox>
                </fieldset>
            </td>
        </tr>
        <tr>
            <td>
                <fieldset id="fsBancoDeDados">
                    <legend>Banco De Dados</legend>
                    <fieldset id="fsPesquisaInseri">
                        <asp:Label ID="lblJogos" runat="server" Text="Jogo Escolhido:"></asp:Label>
                        <asp:TextBox ID="txtJogos" runat="server"></asp:TextBox>
                    </fieldset>
                    <fieldset id="fsGridBancoDeDados">
                        <legend>Dados Provenientes Do Banco</legend>
                        <asp:GridView ID="dtgdvwJogos" runat="server" 
                             AutoGenerateDeleteButton ="True"
                             AutoGenerateEditButton ="True"
                             AutoGenerateSelectButton ="True" 
                             OnPageIndexChanging="dtgdvwJogos_PageIndexChanging" 
                             OnRowDeleting="dtgdvwJogos_RowDeleting"
                             OnRowEditing="dtgdvwJogos_RowEditing"
                             OnRowUpdating="dtgdvwJogos_RowUpdating"
                             OnRowCancelingEdit="dtgdvwJogos_RowCancelingEdit"
                             OnSelectedIndexChanged="dtgdvwJogos_SelectedIndexChanged"
                            ></asp:GridView>
                    </fieldset>
                </fieldset>
            </td>
        </tr>
    </table>

    <h3>Sugerimos o seguinte:</h3>
    <ol class="round">
        <li class="one">
            <h5>Começando</h5>
            O ASP.NET Web Forms permite criar sites dinâmicos usando um modelo familiar de arrastar e soltar, orientado a eventos. 
            Uma superfície de design e centenas de controles e componentes permitem criar rapidamente sites sofisticados e poderosos, orientados por interface do usuário, com acesso a dados.
            <a href="http://go.microsoft.com/fwlink/?LinkId=245146">Saber mais…</a>
        </li>
        <li class="two">
            <h5>Adicione pacotes NuGet e inicie a sua codificação</h5>
            O NuGet facilita a instalação e atualização de bibliotecas e ferramentas gratuitas.
            <a href="http://go.microsoft.com/fwlink/?LinkId=245147">Saber mais…</a>
        </li>
        <li class="three">
            <h5>Encontre Hospedagem na Web</h5>
            Você pode encontrar facilmente uma empresa de hospedagem na web que oferece a combinação certa de recursos e preços para seus aplicativos.
            <a href="http://go.microsoft.com/fwlink/?LinkId=245143">Saber mais…</a>
        </li>
    </ol>
</asp:Content>
