<%@ Page Title="Pagina Familiar" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Familiar.aspx.cs" Inherits="treinamentoInicialAspNetCompleto.Familiar" %>
<asp:Content ID="HeadFamiliarContent" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        #dvPesquisaFamiliar
        {
            width: 276px;
            height: 86px;
        }
        .auto-style1
        {
            width: 674px;
            height: 268px;
        }
        .auto-style2
        {
            width: 410px;
            height: 268px;
        }
        #dvCadastro
        {
            width: 307px;
            height: 735px;
        }
    </style>
</asp:Content>
<asp:Content ID="FamiliarFeatureContent" ContentPlaceHolderID="FeaturedContent" runat="server">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1><%: Title %>. FAMÍLIA - </h1>
                <h2>Gestão de Familiares.</h2>
            </hgroup>
            <p>
                Para saber mais sobre o ASP.NET, visite <a href="http://asp.net" title="ASP.NET Website">http://asp.net</a>.
                A página apresenta <mark>vídeos, tutoriais e amostras</mark> para ajudá-lo a obter o máximo do ASP.NET.
                Se você tiver alguma dúvida sobre o ASP.NET, visite
                <a href="http://forums.asp.net/18.aspx" title="ASP.NET Forum">nossos fóruns</a>.
            </p>
        </div>'
    </section>
</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <table>
        <tr>
            <td class="auto-style2">
                <div id="dvControleFamiliar">
                    <fieldset id="fsBancoDeDadosFamiliar">
                        <legend>Banco De Dados</legend>
                        <fieldset id="fsPesquisaInseriFamiliar">
                            <legend></legend>
                            <asp:Label ID="lblFamiliar" runat="server" Text="Familiar Escolhido:"></asp:Label>
                                <div ID="dvPesquisaFamiliar" class="dvPesquisaFamiliar">
                                    <asp:TextBox ID="txtFamiliar" runat="server" Width="149px"></asp:TextBox>
                                    <asp:Button ID="btnPesquisa" runat="server" Text="Pesquisar" OnClick="btnPesquisa_Click"/>
                                    <asp:Button ID="btnInserirFamiliar" runat="server" Text="Novo Familiar" OnClick="btnInserirFamiliar_Click" />
                                </div>
                        </fieldset>
                    </fieldset>
                </div>
            </td>
            <td class="auto-style1">
                <div id="dvCadastro">
                    <fieldset id="fsCadastro">
                        <legend>Dados para cadastro de Familair</legend>
                            <asp:Label ID="lblNome" runat="server" Text="Nome"></asp:Label>
                            <asp:TextBox ID="txtNome" runat="server" Width="238px"></asp:TextBox>
                            <asp:Label ID="lblSexo" runat="server" Text="Sexo"></asp:Label>
                            <asp:TextBox ID="txtSexo" runat="server" Width="238px"></asp:TextBox>
                            <asp:Label ID="lblIdade" runat="server" Text="Idade"></asp:Label>
                            <asp:TextBox ID="txtIdade" runat="server" Width="238px"></asp:TextBox>
                            <asp:Label ID="lblGanhoMensal" runat="server" Text="GanhoMensal"></asp:Label>
                            <asp:TextBox ID="txtGanhoMensal" runat="server" Width="238px"></asp:TextBox>
                            <asp:Label ID="lblGastoMensal" runat="server" Text="GastoMensal"></asp:Label>
                            <asp:TextBox ID="txtGatoMensal" runat="server" Width="238px"></asp:TextBox>
                            <asp:Label ID="lblObservacao" runat="server" Text="Observação"></asp:Label>
                            <asp:TextBox ID="txtObservacao" runat="server" Width="238px"></asp:TextBox>
                            <asp:Button ID="btnSalvar" runat="server" Text="Salvar" OnClick="btnSalvar_Click" />
                            <asp:Button ID="btnCancelar" runat="server" Text="Cancelar" OnClick="btnCancelar_Click" />
                    </fieldset>
                </div>  
            </td>                             
        </tr>
        <tr>
            <td colspan="2">
                <div id="dvGridFamiliar">
                     <fieldset id="fsGridBancoDeDadosFamiliar">
                            <legend>Dados Provenientes Do Banco</legend>
                            <asp:GridView ID="dtgdvwFamiliar" runat="server"
                                AutoGenerateDeleteButton="True"
                                AutoGenerateEditButton="True"
                                AutoGenerateSelectButton="True"
                                OnPageIndexChanging="dtgdvwFamiliar_PageIndexChanging"
                                OnRowDeleting="dtgdvwFamiliar_RowDeleting"
                                OnRowEditing="dtgdvwFamiliar_RowEditing"
                                OnRowUpdating="dtgdvwFamiliar_RowUpdating"
                                OnRowCancelingEdit="dtgdvwFamiliar_RowCancelingEdit"
                                OnSelectedIndexChanged="dtgdvwFamiliar_SelectedIndexChanged" Width="547px">
                            </asp:GridView>
                      </fieldset>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>
